version: '3.3'

services:
  redis:
    image: redis:alpine
    restart: always
    read_only: true
    deploy:
      resources:
        limits:
          memory: 30m
          cpus: "1"
        reservations:
          memory: 10m
          cpus: ".1"
      labels:
        traefik.enable: "false"
    volumes:
      - type: tmpfs
        target: /tmp
    networks:
      - database

  nextdb:
    image: postgres:alpine
    restart: always
    read_only: true
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: "2"
        reservations:
          memory: 50M
          cpus: ".5"
      labels:
        traefik.enable: "false"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg-root-password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - type: tmpfs
        target: /run/postgresql
      - type: tmpfs
        target: /tmp
      - pgdata:/var/lib/postgresql/data
    secrets:
      - pg-root-password
    networks:
      - database

  app:
    image: nextcloud:fpm
    restart: always
    #read_only: true
    # Writes a single file to /usr/local/etc/php/conf.d for redis
    deploy:
      resources:
        limits:
          memory: 250m
          cpus: "2"
        reservations:
          memory: 50m
          cpus: ".25"
      labels:
        traefik.enable: "false"
    environment:
      ENV_SECRETS_DEBUG: 1
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/nextcloud-admin-password
      NEXTCLOUD_ADMIN_USER: docker
      NEXTCLOUD_UPDATE: 1
      POSTGRES_DB: nextcloud
      POSTGRES_HOST: nextdb
      POSTGRES_PASSWORD_FILE: /run/secrets/pg-root-password
      POSTGRES_USER: postgres
      REDIS_HOST: redis
    command:
      - /usr/bin/env
      - bash
      - /run/secrets/secrets-cmd-v1
      - php-fpm
    depends_on:
      - db
      - redis
    secrets:
      - secrets-cmd-v1
      - pg-root-password
      - nextcloud-admin-password
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_config:/var/www/html/config
      - type: tmpfs
        target: /tmp
    # FIXME: This breaks config, so find a new way.
    # configs:
    #  - source: s3_config
    #    target: /var/www/html/config/s3.config.php
    networks:
      - database

  web:
    image: nginx:stable-alpine
    read_only: true
    restart: always
    depends_on:
      - app
    deploy:
      resources:
        limits:
          memory: 20M
          cpus: "0.25"
        reservations:
          memory: 5M
          cpus: "0.1"
      labels:
        traefik.backend: "web"
        traefik.docker.network: "traefik-public"
        traefik.enable: "true"
        traefik.frontend.rule: "${TR_FRONT}"
        traefik.port: 80
        traefik.redirectorservice.frontend.entryPoints: "http"
        traefik.redirectorservice.frontend.redirect.entryPoint: "https"
        traefik.tags: "traefik-public"
        traefik.webservice.frontend.entryPoints: "https"
    volumes:
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /var/cache/nginx
      - type: tmpfs
        target: /tmp
      - type: bind
        source: nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - nextcloud:/var/www/html:ro
      - nextcloud_config:/var/www/html/config:ro
    networks:
      - database
      - traefik-public

volumes:
  nextcloud:
  nextcloud_config:
  pgdata:

networks:
  traefik-public:
    external: true
  database:
    driver: overlay

secrets:
  pg-root-password:
    file: secrets/.pgroot
  secrets-cmd-v1:
    file: ./secrets.sh
  nextcloud-admin-password:
    file: secrets/.ncroot

configs:
  s3_config:
    file: ./config.d/s3.config.php
